export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const SET_BOOKS = 'SET_BOOKS';
export const SET_GENRE = 'SET_GENRE';
export const FETCH_BOOKS_FAILED = 'FETCH_BOOKS_FAILED';
export const INIT_BOOKS_LIST = 'INIT_BOOKS_LIST';